language: python
python:
  "3.7"
services:
  postgresql
before_script:
  - psql -d postgres -c '\i sql/dbdump.sql;' -U postgres
  - psql -c "alter user postgres with password 'postgrepass';" -U postgres
install:
  - pip3 install -r swagger_server/requirements.txt
script:
  - cd test/
  - python3 test_updater.py
  - python3 test.py
