# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.week import Week
from swagger_server import util


class ProfessorWeek(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, name: str=None, schedule: Week=None):  # noqa: E501
        """ProfessorWeek - a model defined in Swagger

        :param name: The name of this ProfessorWeek.  # noqa: E501
        :type name: str
        :param schedule: The schedule of this ProfessorWeek.  # noqa: E501
        :type schedule: Week
        """
        self.swagger_types = {
            'name': str,
            'schedule': Week
        }

        self.attribute_map = {
            'name': 'name',
            'schedule': 'schedule'
        }

        self._name = name
        self._schedule = schedule

    @classmethod
    def from_dict(cls, dikt) -> 'ProfessorWeek':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ProfessorWeek of this ProfessorWeek.  # noqa: E501
        :rtype: ProfessorWeek
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self) -> str:
        """Gets the name of this ProfessorWeek.


        :return: The name of this ProfessorWeek.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this ProfessorWeek.


        :param name: The name of this ProfessorWeek.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def schedule(self) -> Week:
        """Gets the schedule of this ProfessorWeek.


        :return: The schedule of this ProfessorWeek.
        :rtype: Week
        """
        return self._schedule

    @schedule.setter
    def schedule(self, schedule: Week):
        """Sets the schedule of this ProfessorWeek.


        :param schedule: The schedule of this ProfessorWeek.
        :type schedule: Week
        """
        if schedule is None:
            raise ValueError("Invalid value for `schedule`, must not be `None`")  # noqa: E501

        self._schedule = schedule
